services:

  uuid-api:
    hostname: uuid-api
    container_name: uuid-api
    # Map host machine port 2222 to container port 8080
    # Only root can listen on ports below 1024, we use higher-numbered ports
    # since nginx is running under non-root user
    ports:
      - "2222:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    init: true
    restart: always
    volumes:
      # Mount the app config to container in order to keep it outside of the image
      - "../src/instance:/usr/src/app/src/instance"
      # Mount the logging to container
      - "../log:/usr/src/app/log"
      # Mount conf.d on host machine to the nginx conf.d on container
      - "./uuid-api/nginx/conf.d:/etc/nginx/conf.d"
    networks:
      - docker_network
    # Send docker logs to AWS CloudWatch
    logging: 
      driver: awslogs
      options:
        awslogs-region: us-east-1
        awslogs-group: uuid-api-docker-logs
        awslogs-stream: ${LOG_STREAM}

networks:
  # This is the network created by gateway to enable communicaton between multiple docker-compose projects
  docker_network:
    external: true
    name: ${NETWORK_NAME}
